name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  test-default:
    description: 'something defaulted'
    required: true
    default: 'defaulted'
  test-optional-given:
    description: 'something given'
    required: false
  testOptionNotGiven:
    description: 'something missing'
    required: false
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello '${{ inputs.who-to-greet }}'.
      shell: bash
    - run: echo Hello '${{ runner.temp }}'.
      shell: bash
    - id: random-number-generator
      #run: echo "::set-output name=random-number::$(echo $RANDOM)"
      run: echo -e "::set-output name=random-number::not-so-much a random-number\n\nsome more"
      shell: bash
    - run: |
        # Note, we're seeing https://git.savannah.gnu.org/cgit/bash.git/tree/CHANGES#n370 :(
        echo '<${{ inputs.test-default }}>'
        echo "$INPUT_OPTION_A"
        echo "$INPUT_OPTION_B"
        [[ -z "$INPUT_OPTION_A" ]] || safeA=$(jq --raw-input --slurp 'rtrimstr("\n")' <<< "$INPUT_OPTION_A")
        [[ -z "$INPUT_OPTION_B" ]] || safeB=$(jq --raw-input --slurp 'rtrimstr("\n")' <<< "$INPUT_OPTION_B")
        json="$(cat <<--
        {
          ${safeA:+$(printf '%s' '"FOO_A"'): $safeA,}
          ${safeB:+$(printf '%s' '"FOO_B"'): $safeB,}
          "foo": "bar"
        }
        -
        )";
        echo "<$json>"
        cat <<< "<$json>"
        jq . <<< "$json"
      shell: bash
      env:
        INPUT_OPTION_A: ${{ inputs.test-optional-given }}
        INPUT_OPTION_B: ${{ inputs.test-OptionNotGiven }}
    #- run: "echo A with: '${{ inputs.secret_a }}'."
      #with:
      #  secret_a: ${{ secrets.TEST_SECRET_A }}
    #  shell: bash
    #- name: foo
    #  env:
    #    secret_a: ${{ secrets.TEST_SECRET_A }}
    #  run: "echo A end: '${{ env.secret_a }}'."
    #  shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
