on:
  workflow_dispatch:
    inputs:
      url:
        description: stuff
        required: true
      text:
        description: stuff too
        required: true
      name:
        description: blah
        required: false

jobs:
  test_relative:
    runs-on: ubuntu-latest
    name: Testing self
    steps:
      - uses: actions/checkout@v3
      - name: Mask sensitive data
        run: |
          jq -e .inputs.url "$GITHUB_EVENT_PATH"
          echo "::add-mask::$(jq -er .inputs.url "$GITHUB_EVENT_PATH")"
        env:
          SECRET_URL: ${{ secrets[github.event.inputs.url] }}
      - name: Run our own action
        uses: ./
        with:
          who-to-greet: |
            [
              {
                "foo": "${{ github.event.inputs.url }}",
                "baz": 123
              ]
            ]
          test-optional-given: "My \"optional\" value\'s the {best} :).\nFor sure!"
