on: [push]

jobs:
  test_v1:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}'
      - id: foo
        uses: pcolby/hello-world-composite-action@v1
        with:
          who-to-greet: |
            [
              {
                "foo": "${{ github.ref_name }}",
                "baz": 123
              ]
            ]
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  test_secret_v1:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: pcolby/hello-world-composite-action@v1
        with:
          who-to-greet: ${{ secrets.TEST_SECRET_A }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  test_relative:
    runs-on: ubuntu-latest
    name: Testing self
    steps:
      - uses: actions/checkout@v3
      - name: Run our own action
        uses: ./
        with:
          who-to-greet: |
            [
              {
                "foo": "${{ github.ref_name }}",
                "baz": 123
              ]
            ]
          test-optional-given: "My \"optional\" value\'s the {best} :).\nFor sure!"

  test_secret_relative:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./
        with:
          who-to-greet: ${{ secrets.TEST_SECRET_A }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  test-links:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/workflows/foo.sh
      - run: ./bin/test-symlink-1.sh
      - run: ./bin/test-symlink-2.sh
      - run: ./tmp/test-symlink-2.sh
      - run: ./tmp/workflows/foo.sh
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
      fail-fast: false

  inspect_runners:
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          bash --version
          set -o
        shell: bash
      - name: should pass
        run: true
        shell: bash
      - name: should fail A
        run: |
          echo before
          [[ a == b ]]
          echo $?
          echo after
          echo 'should not get here!'
        shell: bash
      - name: should fail B
        run: |
          echo before
          [[ a == b ]] || false
          echo $?
          echo after
          echo 'should not get here!'
        shell: bash
      - name: should fail C
        run: |
          echo before
          [[ a == b ]] || exit
          echo $?
          echo after
          echo 'should not get here!'
        shell: bash
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
      fail-fast: false
